# Generated by Django 5.0.1 on 2024-01-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitsMaster',
            fields=[
                ('fruit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='フルーツID')),
                ('fruit_name', models.CharField(max_length=20, verbose_name='フルーツ名')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='FruitsSalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=20, verbose_name='フルーツ名')),
                ('sales', models.IntegerField(verbose_name='売り上げ数')),
                ('total', models.IntegerField(verbose_name='売り上げ金額')),
                ('sales_at', models.DateTimeField(verbose_name='販売日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
